#!/bin/sh


if [ "$1" = "start" ] && [ "$(nvram get ntp_ready)" = "0" ]; then
        # Wait for NTP before starting
        ntptimer=0
        while [ "$ntptimer" -lt "60" ]; do
                ntptimer=$((ntptimer+1))
                [ "$ntptimer" -eq "1" ] && logger -st "S61unbound" "Waiting for NTP to sync before starting Unbound..."
                sleep 1
        done
        if [ "ntptimer" -gt "60" ]; then
                local NW_STATE
                local RES_STATE
                ping 1.1.1.1 -c1 -W2 >/dev/null 2>&1
                NW_STATE=$?
                nslookup google.com >/dev/null 2>&1
                RES_STATE=$?
                if [ -z "`pidof unbound`" ]; then
                        logger -st "S61unbound" "Warning: unbound is dead"
                        /opt/etc/init.d/S61unbound start && exit
                elif [ $NW_STATE -eq 0 ] && [ $RES_STATE -ne 0 ]; then
                        logger -st "S61unbound" "Warning: unbound is not responding"
                        /opt/etc/init.d/S61unbound start && exit
                fi
        fi
fi

# set environment PATH to system binaries
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:$PATH
export TZ=$(cat /etc/TZ)
ENABLED=yes
PROCS=unbound
ARGS="-c /opt/var/lib/unbound/unbound.conf"
PREARGS="nohup"
PRECMD=""
POSTCMD="service restart_dnsmasq"
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
