#!/bin/sh

# set environment PATH to system binaries
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:$PATH
export TZ=$(cat /etc/TZ)
ENABLED=yes
PROCS=unbound
ARGS="-c /opt/var/lib/unbound/unbound.conf"
PREARGS="nohup"
PRECMD=""
POSTCMD="service restart_dnsmasq"
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

if [ "$1" = "start" ]; then
        # Wait for NTP before starting
        ntptimer=0
        while [ "$(nvram get ntp_ready)" = "0" ] || [ "$ntptimer" -lt "5" ]; do
                ntptimer=$((ntptimer+1))
                [ "$ntptimer" -eq "1" ] && logger -st "S61unbound" "Starting Unbound Monitor."
                
                sleep 1
        done
        
        . /opt/etc/init.d/rc.func && logger -st "S61unbound" "Starting Unbound DNS server $0"
        
        while [ "$ntptimer" -ge "5" ]; do
                local NW_STATE
                local RES_STATE
                ping 1.1.1.1 -c1 -W2 >/dev/null 2>&1
                NW_STATE=$?
                nslookup google.com >/dev/null 2>&1
                RES_STATE=$?
                if [ -z "`pidof unbound`" ]; then
                        logger -st "S61unbound" "Warning: unbound is dead"
                        /opt/etc/init.d/S61unbound restart
                elif [ $NW_STATE -eq 0 ] && [ $RES_STATE -ne 0 ]; then
                        logger -st "S61unbound" "Warning: unbound is not responding"
                        /opt/etc/init.d/S61unbound restart
                fi
                sleep 10
        done
elif [ "$1" = "restart" ]; then
. /opt/etc/init.d/rc.func && logger -st "S61unbound" "Restarting Unbound DNS server $0"
elif [ "$1" = "stop" ]; then
. /opt/etc/init.d/rc.func && logger -st "S61unbound" "Stopping Unbound DNS server $0"
fi
#for any other arguements
. /opt/etc/init.d/rc.func
